export enum EnumAuthTtlEnv {
    ACCESS = 'JWT_ACCESS_EXPIRES_IN',
    REFRESH = 'JWT_REFRESH_EXPIRES_IN',
    PASSWORD_RESET = 'PASSWORD_RESET_EXPIRES_IN',
    ACCESS_COOKIE = 'AUTH_ACCESS_COOKIE_MAX_AGE',
    REFRESH_COOKIE = 'AUTH_REFRESH_COOKIE_MAX_AGE',
    TOKEN_CLEANUP_LOCK = 'AUTH_TOKEN_CLEANUP_LOCK_TTL',
    LIVEKIT_CALL_TOKEN = 'LIVEKIT_CALL_TOKEN_EXPIRES_IN',
}

/** Default TTLs used when env overrides are not set. */
export const AUTH_DEFAULT_TTL = {
    ACCESS: '15m',
    REFRESH: '30d',
    PASSWORD_RESET: '30m',
    TOKEN_CLEANUP_LOCK: '10m',
    LIVEKIT_CALL_TOKEN: '6h',
} as const;
