export {
    AUTH_DEFAULT_TTL,
    EnumAuthTtlEnv,
} from '@/lib/auth/auth-token-lifetime.config';

export enum EnumAuthErrorCode {
    // Access Token
    ACCESS_TOKEN_MISSING = 'ACCESS_TOKEN_MISSING',
    ACCESS_TOKEN_EXPIRED = 'ACCESS_TOKEN_EXPIRED',
    ACCESS_TOKEN_INVALID = 'ACCESS_TOKEN_INVALID',
    ACCESS_TOKEN_ERROR = 'ACCESS_TOKEN_ERROR',

    // Refresh Token
    REFRESH_TOKEN_MISSING = 'REFRESH_TOKEN_MISSING',
    REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED',
    REFRESH_TOKEN_INVALID = 'REFRESH_TOKEN_INVALID',
    REFRESH_TOKEN_NOT_FOUND = 'REFRESH_TOKEN_NOT_FOUND',
    REFRESH_TOKEN_ERROR = 'REFRESH_TOKEN_ERROR',

    // Session / record
    TOKEN_USER_MISMATCH = 'TOKEN_USER_MISMATCH',
    TOKEN_NOT_FOUND = 'TOKEN_NOT_FOUND',

    // User
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    USER_NOT_ACTIVATED = 'USER_NOT_ACTIVATED',
    INVALID_PASSWORD = 'INVALID_PASSWORD',

    // Password reset / change
    PASSWORD_RESET_TOKEN_INVALID = 'PASSWORD_RESET_TOKEN_INVALID',
    PASSWORD_RESET_TOKEN_EXPIRED = 'PASSWORD_RESET_TOKEN_EXPIRED',
    PASSWORD_RESET_TOKEN_USED = 'PASSWORD_RESET_TOKEN_USED',
    PASSWORD_SAME_AS_OLD = 'PASSWORD_SAME_AS_OLD',

    // Sessions
    SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
}

export enum EnumAuthSecrets {
    ACCESS_TOKEN = 'JWT_ACCESS_SECRET',
    REFRESH_TOKEN = 'JWT_REFRESH_SECRET',
}
