export enum EnumAuthErrorCode {
    ACCESS_TOKEN_MISSING = 'ACCESS_TOKEN_MISSING',
    ACCESS_TOKEN_EXPIRED = 'ACCESS_TOKEN_EXPIRED',
    ACCESS_TOKEN_INVALID = 'ACCESS_TOKEN_INVALID',
    REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED',
    REFRESH_TOKEN_INVALID = 'REFRESH_TOKEN_INVALID',
    ACCESS_TOKEN_ERROR = 'ACCESS_TOKEN_ERROR',
    REFRESH_TOKEN_ERROR = 'REFRESH_TOKEN_ERROR',
  }

  export enum EnumAuthSecrets {
    ACCESS_TOKEN = 'JWT_ACCESS_SECRET',
    REFRESH_TOKEN = 'JWT_REFRESH_SECRET',
  }
